const stations=[
["AIR Malayalam","All India Radio","news","📻"],["Akashvani Kochi","Kochi","fm","📻"],["FM Rainbow Kochi","Kochi","fm","🌈"],["Akashvani Kannur","Kannur","fm","📻"],["Akashvani Calicut","Kozhikode","news","📻"],["Akashvani Kozhikode Real FM","Kozhikode","fm","📻"],["Akashvani Manjeri","Manjeri","fm","📻"],["Akashvani Thrissur","Thrissur","fm","📻"],["Akashvani Kerala","Kerala","news","📻"],["Akashvani Devikulam","Devikulam","fm","📻"],["Vividh Bharati Malayalam","Kerala","music","🎙️"],["Club FM 94.3","Kochi","music","🎙️"],["Radio Mango 91.9","Kochi","music","🥭"],["Red FM 93.5","Kochi","music","🔴"],["Radio Mirchi","Kochi","music","🎧"],["Jaihind Radio","Kerala","news","📡"],["Kairali FM","Thiruvananthapuram","talk","📻"],["Mathrubhumi Radio","Kerala","news","📰"]];
const audio=document.querySelector("#audio"),grid=document.querySelector("#grid");let current=-1;
function render(list=stations){grid.innerHTML=list.map(s=>{let i=stations.indexOf(s);return `<article class="card"><div class="top"><span class="tag">LIVE</span><span>🇮🇳</span></div><div class="logo">${s[3]}</div><h3>${s[0]}</h3><p>${s[1]}</p><div class="bottom"><span class="un" id="u${i}"></span><button class="mini" onclick="playStation(${i})">▶</button></div></article>`}).join("")}
window.playStation=function(i){current=i;let s=stations[i];document.querySelector("#name").textContent=s[0];document.querySelector("#location").textContent=s[1];document.querySelector("#art").textContent=s[3];document.querySelector("#now").textContent=s[0];document.querySelector("#status").textContent="UNAVAILABLE";document.querySelector("#play").textContent="▶";document.querySelector("#u"+i).textContent="Live stream unavailable";alert("Live stream is currently unavailable for this station.");};
document.querySelector("#play").onclick=()=>current<0?playStation(0):playStation(current);
document.querySelector("#prev").onclick=()=>current>0&&playStation(current-1);document.querySelector("#next").onclick=()=>current<stations.length-1&&playStation(current+1);
document.querySelector("#volume").oninput=e=>audio.volume=e.target.value;document.querySelector("#theme").onclick=()=>document.body.classList.toggle("dark");
document.querySelector("#search").oninput=e=>{let q=e.target.value.toLowerCase();render(stations.filter(s=>(s[0]+" "+s[1]).toLowerCase().includes(q)))};
document.querySelectorAll(".filters button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filters button").forEach(x=>x.classList.remove("active"));b.classList.add("active");let f=b.dataset.f;render(f==="all"?stations:stations.filter(s=>s[2]===f))});render();